ProjetoAnkiUnivesp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import View
from core import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    url(r'^$', views.index, name="index"),     
    url(r'^contato/$', views.contact, name="contact"),
    url(r'^entrar/$', LoginView.as_view(template_name='login.html'), name='login'), 
    url(r'^sair/$', LogoutView.as_view(next_page = 'index'), name='logout'),  
    url(r'^ajuda/$', views.help, name="help"),
    url(r'^arquivo/$', views.file, name="file"), 
    url(r'^projeto/$', views.project, name="project"),
    url(r'^config_tentativa/$', views.create_attempt, name="config_tentativa"),
    url(r'^tentativa/$', views.list_attempt, name="list_attempt"),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^questoes/', include('core.urls', namespace='core')),   
    # url(r'^questoes/$', views.list_question, name="list_question"),   
    url(r'^materias/$', views.list_theme, name="list_theme"),   
    url(r'^admin/', admin.site.urls),
    #teste
    url(r'^readText/$',views.readText, name="readText"),
    
]

accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

app_name = 'accounts'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register')
]

core/urls.py
from django.urls import path

from .views import list_question, create_question, update_question, delete_question, list_theme, create_theme, delete_theme, update_theme

app_name = "core"

urlpatterns = [
    path('', list_question, name='list_question'),
    path('new', create_question, name='create_question'),
    path('update/<int:id>/', update_question, name='update_question'),
    path('delete/<int:id>/', delete_question, name='delete_question'),
    path('theme', list_theme, name='list_theme'),
    path('newTheme', create_theme, name='create_theme'),
    path('updateTheme/<int:id>/', update_theme, name='update_theme'),
    path('deleteTheme/<int:id>/', delete_theme, name='delete_theme'),
]

core/models.py
from django.db import models
from accounts.models import User

# Create your models here.

class Category(models.Model):
    description = models.CharField(max_length=60, verbose_name='Categoria')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.description

class Theme(models.Model):
    description = models.CharField(max_length=250,verbose_name='Tema')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoria', default=0)

    class Meta:
        db_table = 'theme'
    
    def __str__(self):
        return self.description

    # def __init__(self, *args, **kwargs):
    #     super(Theme, self).__init__(*args, **kwargs)
    #     #self.fields["user"].value = 2
    #     print(User.id)

class Question(models.Model):
    description = models.CharField(max_length=250, null=False, verbose_name='Questão')
    answer = models.CharField(max_length=500, verbose_name='Resposta')
    image = models.TextField(null=True, verbose_name='Imagem')
    public = models.BooleanField(verbose_name='Publica')
    created_at = models.DateTimeField(auto_now_add=True)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, verbose_name='Tema')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='usuários')

    class Meta:
        db_table = 'questions'
    
    def __str__(self):
        return self.description

class Difficults_options(models.IntegerChoices):
    EASY = 1
    MEDIUM = 2
    DIFFICULT = 3 

class Attempt(models.Model):
    attempt_number = models.IntegerField(null=False)
    attempt_date = models.DateTimeField(auto_now_add=True)
    got_it_right = models.BooleanField(verbose_name='acertou')
    difficult = models.IntegerField(choices=Difficults_options.choices, verbose_name='Dificuldade')
    question = models.ForeignKey(Question, on_delete=models.CASCADE,verbose_name='Questão')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='usuários')
    
    class Meta:
        db_table = 'attempts'

    def __str__(self):
        return self.question.description        
    

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import fields
from .models import Question, Theme, Attempt

class ContactForm(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato Projeto Anki-Univesp', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]       
        )

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['description', 'answer', 'theme','public', 'user']

class ThemeForm(forms.ModelForm):
    class Meta:
        model = Theme
        fields = ['description', 'category', 'user']

class AttemptForm(forms.ModelForm):
    class Meta:
        model = Attempt
        fields = ['attempt_number', 'question', 'difficult', 'got_it_right', 'user']        

# class AttemptForm(forms.Form):
#     attempt_number = forms.IntegerField(label='Tentativa')
#     got_it_right = forms.BooleanField(label='acertou')
#     difficult = forms.IntegerField(label='dificuldade')
#     question = forms.ChoiceField(label='questão')
#     user = forms.CharField(label='usuario')

core/views.py
import asyncio
from unicodedata import category
from django.db import models
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from .forms import AttemptForm, ContactForm , QuestionForm, ThemeForm
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView, DetailView, ListView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import Question, Theme, Attempt, Category
from Include import TextToSpeachConverter
from django.utils.encoding import uri_to_iri
import urllib

User = get_user_model()

class IndexView(TemplateView):
    template_name = 'index.html'
index = IndexView.as_view()


@login_required
def contact(request):
    success = False        
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True

    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

def help(request):
    return render(request, 'help.html')

def file(request):
    return render(request, 'file.html')

def project(request):
    user  = request.user
    user_id = user.id
    current_user= User.objects.get(id=user_id)
    user_themes = current_user.theme_set.all()
    return render(request, 'project.html', {'themes': user_themes})

##Classe para acesso as informações da tabela Theme
# class ThemeListView(ListView):
#     model = Theme

# class ThemeDetailView(DetailView):
#     model = Theme

def list_theme(request):
    themes = Theme.objects.all()
    user  = request.user
    user_id = user.id
    current_user= User.objects.get(id=user_id)
    user_themes = current_user.theme_set.all()
    return render(request, 'themes.html', {'themes': user_themes})


def create_theme(request):
    form = ThemeForm(request.POST or None)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('list_theme')

    return render(request, 'themes-form.html', {'form': form})


def update_theme(request, id):
    theme = Theme.objects.get(id=id)
    form = ThemeForm(request.POST or None, instance=theme)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('list_theme')

    return render(request, 'themes-form.html', {'form': form, 'theme': theme})


def delete_theme(request, id):
    theme = Theme.objects.get(id=id)
    if request.method == 'POST':
        theme.delete()
        return redirect('list_theme')

    return render(request, 'theme-delete-form.html', {'theme': theme})


##Classe para acesso as informações da tabela Question
# class QuestionListView(ListView):
#     model = Question

# class QuestionDetailView(DetailView):
#     model = Question

def list_question(request):
    questions = Question.objects.all()
    user  = request.user
    user_id = user.id
    current_user= User.objects.get(id=user_id)
    user_questions = current_user.question_set.all()
    return render(request, 'questions.html', {'questions': user_questions})


def create_question(request):
    form = QuestionForm(request.POST or None)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('core:list_question')

    return render(request, 'questions-form.html', {'form': form})


def update_question(request, id):
    question = Question.objects.get(id=id)
    form = QuestionForm(request.POST or None, instance=question)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('core:list_question')

    return render(request, 'questions-form.html', {'form': form, 'question': question})


def delete_question(request, id):
    question = Question.objects.get(id=id)

    if request.method == 'POST':
        question.delete()
        return redirect('core:list_question')

    return render(request, 'question-delete-form.html', {'question': question})

##Classe para acesso as informações da tabela Attempt
# class AttemptListView(ListView):
#     model = Attempt

# class AttemptDetailView(DetailView):
#     model = Attempt

def list_attempt(request):
    questionCount = 0
    user  = request.user
    user_id = user.id
    current_user = User.objects.get(id=user_id)
    # attempts = Attempt.objects.filter(attempt_number=1,user=user_id)
    lastAttempt = current_user.attempt_set.order_by('-attempt_number')[0]
    attempts = Attempt.objects.filter(attempt_number=lastAttempt.attempt_number,user=user_id)
    Convert = TextToSpeachConverter.TextToSpeachConverterPyttsx3()

    # attempts = AttemptForm(request.POST or None, instance=antes)
    if request.POST:
        for value in request.POST:

            if (value != 'csrfmiddlewaretoken'):
                x = value.split("_")
                id = x[1]
                updateAttempt = Attempt.objects.get(id=id)
                #Ao salvar (finalizar a tentativa) fala a pergunta e as respostas.
                #Convert.ConvertAndPlay('Pergunta: ' + updateAttempt.question.description)
                #Convert.ConvertAndPlay('Resposta: ' + updateAttempt.question.answer)
             
                if (value == 'got-it-right_'+id):
                    updateAttempt.got_it_right = 1
                    updateAttempt.save()
                if (value == 'difficult_'+id):
                    updateAttempt.difficult = int(request.POST[value])
                    updateAttempt.save()

        return render(request, 'alert.html', {'no_record_check': 1})

    # Falar as perguntas geradas
    for attempt in attempts:
        Convert.ConvertAndPlay('Pergunta ' + str(questionCount) + ':' +  attempt.question.description)
        questionCount += 1

    return render(request, 'attempts.html', {'attempts': attempts})


def create_attempt(request):
    user  = request.user
    user_id = user.id

    current_user = User.objects.get(id=user_id)
    user_themes = current_user.theme_set.all()
    categories = Category.objects.all()
    if request.POST:
        quantidade_select = request.POST['quantidade_perguntas']
        themeId = request.POST['decks']
        categoryId = request.POST['categoria']
        publicQuestionsOn = 'aceita_publica' in request.POST
        theme = Theme.objects.get(id=themeId)
        themeCategory = Theme.objects.filter(category = categoryId)
        
        #verifica quantas tentativas (quiz) já foram geradas para este usuário, para pegar o valor da nova tentativa.
        if current_user.attempt_set.count() > 0:
            lastAttempt = current_user.attempt_set.order_by('-attempt_number')[0]
            if lastAttempt.attempt_number :
                thisAttempt = lastAttempt.attempt_number + 1
        else:
            thisAttempt = 1

        #Verifica se no formulário o usuário marcou que irá usar as perguntas publicas para querar seu quiz de estudo
        if publicQuestionsOn:
            questions = current_user.question_set.all().filter(theme=theme).order_by('?') | Question.objects.filter(public = 1).filter(theme__in=themeCategory).order_by('?')
            questions = questions.order_by('?')[:int(quantidade_select)]
        else:
            questions = current_user.question_set.all().filter(theme=theme).order_by('?')[:int(quantidade_select)]
        count = 0
        length = questions.count()
        if length <= 0:
            return render(request,'alert.html', {'no_record_check': 0})       
        
        for question in questions:
            attempt = Attempt(attempt_number = int(thisAttempt), got_it_right=0 , difficult=0,question=question, user = current_user)
            attempt.save()
            count += 1
            if count == length:
                return redirect('list_attempt') 

    return render(request, 'create_attempts.html', {'themes': user_themes, 'categories': categories})

def readText(request):
   # print (request.GET)
    decodeTextUrl = urllib.parse.unquote(str(request.GET['text']))
    Convert = TextToSpeachConverter.TextToSpeachConverterPyttsx3()
    #print('----------------------------+++++++++------------------')
    #print(urllib.parse.unquote(str(request.GET['text'])))
    Convert.ConvertAndPlay(decodeTextUrl)
    data={'valor':'teste'}
    return JsonResponse(data)

core/templates/alert.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Realizar tentativa | {{ block.super }}
{% endblock %}
{% block container %}

<div>
    <br>
    <br>
    {% if no_record_check > 0 %}
        <div class="alert alert-success">
            <strong>Parabens processo concluido </strong>
        </div>
    {% else %}
        <div class="alert alert-warning">
            <strong> Não há nenhum Card cadastrado. Gentileza cadastre algum card. </strong>
        </div>
    {% endif %}
</div>

<div><a href="{% url 'index' %}"><button class="btn btn-primary">Página Principal</button></a></div>

{% endblock %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Projeto Anki Univesp{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/css/custom.min.css' %}" media="screen" /> 
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Projeto SEREI</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="{% url 'index' %}">Início</a>
            </li>  
            {% if user.is_authenticated %}
            <!-- <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'file' %}" id="download">Editar<span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="{% url 'file' %}">Desfazer</a></li>                
              </ul>
            </li>                 -->
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'file' %}" id="download">Cadastros <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="{% url 'core:list_question' %}">Criar Baralho</a></li>
                <li><a href="{% url 'core:list_theme' %}">Temas dos baralhos</a></li>
              </ul>
            </li>
            {% endif %}
            <!-- <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'file' %}" id="download">Ajuda<span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="{% url 'file' %}">Guia</a></li>
                <li><a href="{% url 'file' %}">Contribua Conosco</a></li>
                <li><a href="{% url 'file' %}">Sobre</a></li>                
              </ul>
            </li>  -->
              <li>
                <a href="{% url 'contact' %}">Contato</a>
             </li>   
            </ul>
            <ul class="nav navbar-nav navbar-right">
             
              <li> <button type="button" class="btn btn-primary alignment-center" id="sound-button" name="sound-button"> <span class="glyphicon glyphicon-volume-up" aria-hidden="true"> </span> </button> </li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Sair</a></li>
              {% else %}
              <li><a href="{% url 'login' %}">Entrar</a></li>               
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'accounts:register' %}" id="download">Cadastro<span class="caret"></span></a>
                <ul class="dropdown-menu" aria-labelledby="download">
                  <li><a href="{% url 'accounts:register' %}">Cadastrar usuário</a></li>                  
                  <li><a href="{% url 'accounts:index' %}">Alterar dados usuário</a></li>                  
                </ul>
              </li>             
              {% endif %}
            </ul>
        </div>
      </div>
    </div>    
    <div class="container margin-top">    
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li><a href="{% url 'index' %}">Início</a></li>			      
			      <li><a href="{% url 'contact' %}">Contato</a></li>
            <li><a href="{% url 'file' %}">Preferências</a></li>
			      <li><a href="{% url 'file' %}">Termos e Privacidade</a></li>    
			    </ul>           
			  </div> 
        <div>
          <ul>
            <li class="django-social">
              <a href="https://api.whatsapp.com/send?phone=5519999999999&text=Texto%20aqui"
              target="_blank">
              <svg enable-background="new 0 0 512 512" width="30" height="30" version="1.1" viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><path d="M256.064,0h-0.128l0,0C114.784,0,0,114.816,0,256c0,56,18.048,107.904,48.736,150.048l-31.904,95.104  l98.4-31.456C155.712,496.512,204,512,256.064,512C397.216,512,512,397.152,512,256S397.216,0,256.064,0z" fill="#4CAF50"/><path d="m405.02 361.5c-6.176 17.44-30.688 31.904-50.24 36.128-13.376 2.848-30.848 5.12-89.664-19.264-75.232-31.168-123.68-107.62-127.46-112.58-3.616-4.96-30.4-40.48-30.4-77.216s18.656-54.624 26.176-62.304c6.176-6.304 16.384-9.184 26.176-9.184 3.168 0 6.016 0.16 8.576 0.288 7.52 0.32 11.296 0.768 16.256 12.64 6.176 14.88 21.216 51.616 23.008 55.392 1.824 3.776 3.648 8.896 1.088 13.856-2.4 5.12-4.512 7.392-8.288 11.744s-7.36 7.68-11.136 12.352c-3.456 4.064-7.36 8.416-3.008 15.936 4.352 7.36 19.392 31.904 41.536 51.616 28.576 25.44 51.744 33.568 60.032 37.024 6.176 2.56 13.536 1.952 18.048-2.848 5.728-6.176 12.8-16.416 20-26.496 5.12-7.232 11.584-8.128 18.368-5.568 6.912 2.4 43.488 20.48 51.008 24.224 7.52 3.776 12.48 5.568 14.304 8.736 1.792 3.168 1.792 18.048-4.384 35.52z" fill="#FAFAFA"/></svg></a>
            </li>
            <li class="django-social">
              <a href="https://www.facebook.com/" target="_blank">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="126.445 2.281 589 589"><circle cx="420.945" cy="296.781" r="294.5" fill="#3c5a9a"/><path fill="#fff" d="M516.704 92.677h-65.239c-38.715 0-81.777 16.283-81.777 72.402.189 19.554 0 38.281 0 59.357H324.9v71.271h46.174v205.177h84.847V294.353h56.002l5.067-70.117h-62.531s.14-31.191 0-40.249c0-22.177 23.076-20.907 24.464-20.907 10.981 0 32.332.032 37.813 0V92.677h-.032z"/>
              </svg></a>
              <li class="django-social">
                <a href="https://www.youtube.com/watch?v=YYScJwvlFog" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 64 64"><path fill="#C8131A" d="M31.999.999C14.879.999 1 14.878 1 32c0 17.12 13.879 31.001 30.999 31.001C49.121 63.001 63 49.12 63 32 63 14.878 49.121.999 31.999.999zM25 41.543V22.458l18.225 9.575L25 41.543z"/><g fill="#E01726"><path d="M41.926 32.724L27 40.499l.331 3.307L45.3 34.467zM3.271 34.435c0-17.122 13.879-31.001 30.999-31.001 8.363 0 15.948 3.317 21.524 8.701C50.108 5.33 41.561.999 31.999.999 14.879.999 1 14.878 1 32c0 8.758 3.638 16.662 9.478 22.301a30.872 30.872 0 01-7.207-19.866z"/></g><path fill="#8E0919" d="M43.216 32.051l-1.846.962-16.297 8.534 19.009 19.009a31.113 31.113 0 0 0 14.695-12.943L43.216 32.051z"/></svg></a>
              </li>
            </li>
          </ul>
        </div>       
			</div>
		</footer>
	</div>  
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso.
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="POST">
      {% csrf_token%}
        <fieldset>

            {% for field in form %}

            <div class="form-group{% if field.errors %} has-error {% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>

            {% endfor %}
            
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/help.html
{% extends "base.html" %}

{% block title %}
    Produto | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Página do Produto</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
      <dl>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
      </dl>
  </div>
</div>
{% endblock %}

core/templates/questions-form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Questões | {{ block.super }}
{% endblock %}
{% block container %}

<div>
    <h1>Novo/Alterar questão</h1>

    <form method="POST">
        {% csrf_token %}
        <!-- {{ form }} -->

        {% for field in form %}
            {% if field.label != 'Usuários'  %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                    
                            {% render_field field class="form-control" %}
                        
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                {% render_field field class="hidden" %}
            {% endif %}
            
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Salvar</button>
            {% if question %}
                <a href="{% url 'core:delete_question' question.id %}"> <button type="button" class="btn deletar" style="background-color:red; color:white">Deletar </button></a>
            {% endif %}
        </div>
        
    </form>



</div>
{% endblock %}

core/templates/questions.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Questões | {{ block.super }}
{% endblock %}
{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Perguntas</h1>
        </div>
        <ul class="list-group">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Pergunta</th>
                    <th scope="col">Tema</th>
                    <th scope="col">Pública</th>
                  </tr>
                </thead>
                <tbody>
            {% for question in questions %}
                  <tr>
                    <td><a href="{% url 'core:update_question' question.id %}">
                            <li class="list-group-item"> {{ question.description }}</li>
                        </a>
                    </td>
                    <td><li class="list-group-item"> {{ question.theme.description }}</li></td>
                    <!-- a função do jango  {{VALUE|yesno:"texto se true, texto se falsez texto caso nulo"}} 
                        pemite configurar respostas padronizadas para valores booleanos -->
                    <td><li class="list-group-item">  {{ question.public|yesno:"SIM,NO,MAYBE" }}   </li></td>
                  </tr>
                
                
            {% endfor %}
                </tbody>
            </table>
        </ul>

        <a href="{% url 'core:create_question' %}"> <button class="btn btn-primary" >  Nova Questão </button></a>
    </div>
</div>
{% endblock %}

core/templates/themes-form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Temas | {{ block.super }}
{% endblock %}
{% block container %}
<div>
    <h1>Novo/Alterar Tema</h1>

    <form method="POST">
        {% csrf_token %}
         <!-- {{ form }} -->
         {% for field in form %}
            {% if field.label != 'User' %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
            <div class="col-md-9">
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            </div>
            {%else%}
                {% render_field field class="form-control hidden" %}
            {% endif %}
        
         {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary ">Salvar</button>
            {% if theme %}
            
                <a href="{% url 'core:delete_theme' theme.id %}"> <button type="button" class="btn deletar" style="background-color:red; color:white"> Deletar </button></a>
            {% endif %}
        </div>
    </form>
   
</div>
{% endblock %}